title: dungtran1228
description: My page
theme: minima

# Minima: custom header links
header_pages:
  - _n2/speed-master/index.md
  - _n2/marugoto/index.md
  - _exam/index.md

include:
    - _n2
    - _exam